In [16]:
import pandas as pd
import seaborn as sb
df=pd.read_csv(r"C:\Users\K.PRABHU\Desktop\NAVEEN NEW\Insurance claims data.csv")

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 41 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   policy_id                         58592 non-null  object
 1   subscription_length               58592 non-null  float64
 2   vehicle_age                       58592 non-null  float64
 3   customer_age                      58592 non-null  int64
 4   region_code                       58592 non-null  object
 5   region_density                    58592 non-null  int64
 6   segment                           58592 non-null  object
 7   model                             58592 non-null  object
 8   fuel_type                         58592 non-null  object
 9   max_torque                        58592 non-null  object
 10  max_power                         58592 non-null  object
 11  engine_type                       58592 non-null  object
 12  airbags                           58592 non-null  int64
 13  is_esc                            58592 non-null  object
 14  is_adjustable_steering            58592 non-null  object
 15  is_tpms                           58592 non-null  object
 16  is_parking_sensors                58592 non-null  object
 17  is_parking_camera                 58592 non-null  object
 18  rear_brakes_type                  58592 non-null  object
 19  displacement                      58592 non-null  int64
 20  cylinder                          58592 non-null  int64
 21  transmission_type                 58592 non-null  object
 22  steering_type                     58592 non-null  object
 23  turning_radius                    58592 non-null  float64
 24  length                            58592 non-null  int64
 25  width                             58592 non-null  int64
 26  gross_weight                      58592 non-null  int64
 27  is_front_fog_lights               58592 non-null  object
 28  is_rear_window_wiper              58592 non-null  object
 29  is_rear_window_washer             58592 non-null  object
 30  is_rear_window_defogger           58592 non-null  object
 31  is_brake_assist                   58592 non-null  object
 32  is_power_door_locks               58592 non-null  object
 33  is_central_locking                58592 non-null  object
 34  is_power_steering                 58592 non-null  object
 35  is_driver_seat_height_adjustable  58592 non-null  object
 36  is_day_night_rear_view_mirror     58592 non-null  object
 37  is_ecw                            58592 non-null  object
 38  is_speed_alert                    58592 non-null  object
 39  ncap_rating                       58592 non-null  int64
 40  claim_status                      58592 non-null  int64
dtypes: float64(3), int64(10), object(28)
memory usage: 18.3+ MB

In [18]:
df.head()

,policy_id,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,max_torque,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status
0,POL045360,9.3,1.2,41,C8,8794,C2,M4,Diesel,250Nm@2750rpm,...,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0
1,POL016745,8.2,1.8,35,C2,27003,C1,M9,Diesel,200Nm@1750rpm,...,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,4,0
2,POL007194,9.5,0.2,44,C8,8794,C2,M4,Diesel,250Nm@2750rpm,...,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0
3,POL018146,5.2,0.4,44,C10,73430,A,M1,CNG,60Nm@3500rpm,...,No,No,No,Yes,No,No,No,Yes,0,0
4,POL049011,10.1,1.0,56,C13,5410,B2,M5,Diesel,200Nm@3000rpm,...,No,Yes,Yes,Yes,No,No,Yes,Yes,5,0

In [19]:
df.isna().sum()

policy_id                           0
subscription_length                 0
vehicle_age                         0
customer_age                        0
region_code                         0
region_density                      0
segment                             0
model                               0
fuel_type                           0
max_torque                          0
max_power                           0
engine_type                         0
airbags                             0
is_esc                              0
is_adjustable_steering              0
is_tpms                             0
is_parking_sensors                  0
is_parking_camera                   0
rear_brakes_type                    0
displacement                        0
cylinder                            0
transmission_type                   0
steering_type                       0
turning_radius                      0
length                              0
width                               0
gross_weight                        0
is_front_fog_lights                 0
is_rear_window_wiper                0
is_rear_window_washer               0
is_rear_window_defogger             0
is_brake_assist                     0
is_power_door_locks                 0
is_central_locking                  0
is_power_steering                   0
is_driver_seat_height_adjustable    0
is_day_night_rear_view_mirror       0
is_ecw                              0
is_speed_alert                      0
ncap_rating                         0
claim_status                        0
dtype: int64

In [20]:
df.dropna()

,policy_id,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,max_torque,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status
0,POL045360,9.3,1.2,41,C8,8794,C2,M4,Diesel,250Nm@2750rpm,...,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0
1,POL016745,8.2,1.8,35,C2,27003,C1,M9,Diesel,200Nm@1750rpm,...,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,4,0
2,POL007194,9.5,0.2,44,C8,8794,C2,M4,Diesel,250Nm@2750rpm,...,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0
3,POL018146,5.2,0.4,44,C10,73430,A,M1,CNG,60Nm@3500rpm,...,No,No,No,Yes,No,No,No,Yes,0,0
4,POL049011,10.1,1.0,56,C13,5410,B2,M5,Diesel,200Nm@3000rpm,...,No,Yes,Yes,Yes,No,No,Yes,Yes,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58587,POL019269,10.6,2.6,48,C5,34738,B2,M6,Petrol,113Nm@4400rpm,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0
58588,POL001254,2.3,2.2,37,C3,4076,C2,M4,Diesel,250Nm@2750rpm,...,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0
58589,POL019859,6.6,2.2,35,C8,8794,B2,M6,Petrol,113Nm@4400rpm,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0
58590,POL014061,4.1,3.6,44,C8,8794,B2,M6,Petrol,113Nm@4400rpm,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0
58591,POL054184,3.1,0.4,49,C12,34791,B2,M6,Petrol,113Nm@4400rpm,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0

In [21]:
df.fillna(0)

,policy_id,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,max_torque,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status
0,POL045360,9.3,1.2,41,C8,8794,C2,M4,Diesel,250Nm@2750rpm,...,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0
1,POL016745,8.2,1.8,35,C2,27003,C1,M9,Diesel,200Nm@1750rpm,...,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,4,0
2,POL007194,9.5,0.2,44,C8,8794,C2,M4,Diesel,250Nm@2750rpm,...,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0
3,POL018146,5.2,0.4,44,C10,73430,A,M1,CNG,60Nm@3500rpm,...,No,No,No,Yes,No,No,No,Yes,0,0
4,POL049011,10.1,1.0,56,C13,5410,B2,M5,Diesel,200Nm@3000rpm,...,No,Yes,Yes,Yes,No,No,Yes,Yes,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58587,POL019269,10.6,2.6,48,C5,34738,B2,M6,Petrol,113Nm@4400rpm,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0
58588,POL001254,2.3,2.2,37,C3,4076,C2,M4,Diesel,250Nm@2750rpm,...,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,3,0
58589,POL019859,6.6,2.2,35,C8,8794,B2,M6,Petrol,113Nm@4400rpm,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0
58590,POL014061,4.1,3.6,44,C8,8794,B2,M6,Petrol,113Nm@4400rpm,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0
58591,POL054184,3.1,0.4,49,C12,34791,B2,M6,Petrol,113Nm@4400rpm,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0

In [22]:
df['is_brake_assist'] = df['is_brake_assist'].map({'Yes': 1, 'No': 0})
df['is_power_door_locks'] = df['is_power_door_locks'].map({'Yes': 1, 'No': 0})
df['is_central_locking'] = df['is_central_locking'].map({'Yes': 1, 'No': 0})
df['is_power_steering'] = df['is_power_steering'].map({'Yes': 1, 'No': 0})
df['is_driver_seat_height_adjustable'] = df['is_driver_seat_height_adjustable'].map({'Yes': 1, 'No': 0})
df['is_day_night_rear_view_mirror'] = df['is_day_night_rear_view_mirror'].map({'Yes': 1, 'No': 0})
df['is_ecw'] = df['is_ecw'].map({'Yes': 1, 'No': 0})
df['is_speed_alert'] = df['is_speed_alert'].map({'Yes': 1, 'No': 0})

In [23]:
df.head()

,policy_id,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,max_torque,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status
0,POL045360,9.3,1.2,41,C8,8794,C2,M4,Diesel,250Nm@2750rpm,...,1,1,1,1,1,0,1,1,3,0
1,POL016745,8.2,1.8,35,C2,27003,C1,M9,Diesel,200Nm@1750rpm,...,0,1,1,1,1,1,1,1,4,0
2,POL007194,9.5,0.2,44,C8,8794,C2,M4,Diesel,250Nm@2750rpm,...,1,1,1,1,1,0,1,1,3,0
3,POL018146,5.2,0.4,44,C10,73430,A,M1,CNG,60Nm@3500rpm,...,0,0,0,1,0,0,0,1,0,0
4,POL049011,10.1,1.0,56,C13,5410,B2,M5,Diesel,200Nm@3000rpm,...,0,1,1,1,0,0,1,1,5,0

In [24]:
from sklearn.preprocessing import LabelEncoder

for col in ['model','fuel_type','region_code','segment','transmission_type','steering_type','rear_brakes_type']:
    df[col] = LabelEncoder().fit_transform(df[col])

In [25]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['engine_type'] = encoder.fit_transform(df['engine_type'])
df['subscription_length']=encoder.fit_transform(df['engine_type'])
df['vehicle_age']=encoder.fit_transform(df['vehicle_age'])
df['turning_radius']=encoder.fit_transform(df['turning_radius'])
df['rear_brakes_type']=encoder.fit_transform(df['rear_brakes_type'])
df['steering_type']=encoder.fit_transform(df['steering_type'])
df['transmission_type']=encoder.fit_transform(df['transmission_type'])

In [26]:
df.head()

,policy_id,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,max_torque,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status
0,POL045360,3,6,41,20,8794,4,5,1,250Nm@2750rpm,...,1,1,1,1,1,0,1,1,3,0
1,POL016745,10,9,35,11,27003,3,10,1,200Nm@1750rpm,...,0,1,1,1,1,1,1,1,4,0
2,POL007194,3,1,44,20,8794,4,5,1,250Nm@2750rpm,...,1,1,1,1,1,0,1,1,3,0
3,POL018146,6,2,44,1,73430,0,0,0,60Nm@3500rpm,...,0,0,0,1,0,0,0,1,0,0
4,POL049011,4,5,56,4,5410,2,6,1,200Nm@3000rpm,...,0,1,1,1,0,0,1,1,5,0

In [27]:
df

,policy_id,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,max_torque,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status
0,POL045360,3,6,41,20,8794,4,5,1,250Nm@2750rpm,...,1,1,1,1,1,0,1,1,3,0
1,POL016745,10,9,35,11,27003,3,10,1,200Nm@1750rpm,...,0,1,1,1,1,1,1,1,4,0
2,POL007194,3,1,44,20,8794,4,5,1,250Nm@2750rpm,...,1,1,1,1,1,0,1,1,3,0
3,POL018146,6,2,44,1,73430,0,0,0,60Nm@3500rpm,...,0,0,0,1,0,0,0,1,0,0
4,POL049011,4,5,56,4,5410,2,6,1,200Nm@3000rpm,...,0,1,1,1,0,0,1,1,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58587,POL019269,8,13,48,17,34738,2,7,2,113Nm@4400rpm,...,1,1,1,1,1,1,1,1,2,0
58588,POL001254,3,11,37,15,4076,4,5,1,250Nm@2750rpm,...,1,1,1,1,1,0,1,1,3,0
58589,POL019859,8,11,35,20,8794,2,7,2,113Nm@4400rpm,...,1,1,1,1,1,1,1,1,2,0
58590,POL014061,8,18,44,20,8794,2,7,2,113Nm@4400rpm,...,1,1,1,1,1,1,1,1,2,0
58591,POL054184,8,2,49,3,34791,2,7,2,113Nm@4400rpm,...,1,1,1,1,1,1,1,1,2,0

In [28]:
df['is_esc'] = df['is_esc'].map({'Yes': 1, 'No': 0})
df['is_adjustable_steering'] = df['is_adjustable_steering'].map({'Yes': 1, 'No': 0})
df['is_tpms'] = df['is_tpms'].map({'Yes': 1, 'No': 0})
df['is_parking_sensors'] = df['is_parking_sensors'].map({'Yes': 1, 'No': 0})
df['is_parking_camera'] = df['is_parking_camera'].map({'Yes': 1, 'No': 0})
df['is_front_fog_lights'] = df['is_front_fog_lights'].map({'Yes': 1, 'No': 0})
df['is_rear_window_wiper'] = df['is_rear_window_wiper'].map({'Yes': 1, 'No': 0})
df['is_rear_window_washer'] = df['is_rear_window_washer'].map({'Yes': 1, 'No': 0})
df['is_rear_window_defogger'] = df['is_rear_window_defogger'].map({'Yes': 1, 'No': 0})

In [29]:
df.head()

,policy_id,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,max_torque,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status
0,POL045360,3,6,41,20,8794,4,5,1,250Nm@2750rpm,...,1,1,1,1,1,0,1,1,3,0
1,POL016745,10,9,35,11,27003,3,10,1,200Nm@1750rpm,...,0,1,1,1,1,1,1,1,4,0
2,POL007194,3,1,44,20,8794,4,5,1,250Nm@2750rpm,...,1,1,1,1,1,0,1,1,3,0
3,POL018146,6,2,44,1,73430,0,0,0,60Nm@3500rpm,...,0,0,0,1,0,0,0,1,0,0
4,POL049011,4,5,56,4,5410,2,6,1,200Nm@3000rpm,...,0,1,1,1,0,0,1,1,5,0

In [30]:
df=df.drop(columns=['policy_id','max_torque','max_power'])

In [31]:
df

,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,engine_type,airbags,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status
0,3,6,41,20,8794,4,5,1,3,6,...,1,1,1,1,1,0,1,1,3,0
1,10,9,35,11,27003,3,10,1,10,2,...,0,1,1,1,1,1,1,1,4,0
2,3,1,44,20,8794,4,5,1,3,6,...,1,1,1,1,1,0,1,1,3,0
3,6,2,44,1,73430,0,0,0,6,2,...,0,0,0,1,0,0,0,1,0,0
4,4,5,56,4,5410,2,6,1,4,2,...,0,1,1,1,0,0,1,1,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58587,8,13,48,17,34738,2,7,2,8,2,...,1,1,1,1,1,1,1,1,2,0
58588,3,11,37,15,4076,4,5,1,3,6,...,1,1,1,1,1,0,1,1,3,0
58589,8,11,35,20,8794,2,7,2,8,2,...,1,1,1,1,1,1,1,1,2,0
58590,8,18,44,20,8794,2,7,2,8,2,...,1,1,1,1,1,1,1,1,2,0
58591,8,2,49,3,34791,2,7,2,8,2,...,1,1,1,1,1,1,1,1,2,0

In [32]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
58587     True
58588     True
58589     True
58590     True
58591     True
Length: 58592, dtype: bool

In [33]:
df.describe()

,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,engine_type,airbags,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status
count,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,...,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000
mean,5.502748,6.937756,44.823935,13.035653,18826.858667,1.938644,4.659237,1.003448,5.502748,3.137066,...,0.549171,0.724246,0.724246,0.979366,0.585251,0.380308,0.724246,0.993805,1.759950,0.063968
std,2.684796,5.622927,6.935604,6.803915,17660.174792,1.566329,3.197355,0.835104,2.684796,1.832641,...,0.497581,0.446897,0.446897,0.142158,0.492683,0.485467,0.446897,0.078467,1.389576,0.244698
min,0.000000,0.000000,35.000000,0.000000,290.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,2.000000,39.000000,6.000000,6112.000000,0.000000,0.000000,0.000000,3.000000,2.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
50%,6.000000,6.000000,44.000000,15.000000,8794.000000,2.000000,5.000000,1.000000,6.000000,2.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,2.000000,0.000000
75%,8.000000,11.000000,49.000000,20.000000,27003.000000,4.000000,7.000000,2.000000,8.000000,6.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,0.000000
max,10.000000,48.000000,75.000000,21.000000,73430.000000,5.000000,10.000000,2.000000,10.000000,6.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.000000,1.000000

In [34]:
X=df.drop("claim_status",axis=1)
Y=df["claim_status"]

In [35]:
X.columns

Index(['subscription_length', 'vehicle_age', 'customer_age', 'region_code',
       'region_density', 'segment', 'model', 'fuel_type', 'engine_type',
       'airbags', 'is_esc', 'is_adjustable_steering', 'is_tpms',
       'is_parking_sensors', 'is_parking_camera', 'rear_brakes_type',
       'displacement', 'cylinder', 'transmission_type', 'steering_type',
       'turning_radius', 'length', 'width', 'gross_weight',
       'is_front_fog_lights', 'is_rear_window_wiper', 'is_rear_window_washer',
       'is_rear_window_defogger', 'is_brake_assist', 'is_power_door_locks',
       'is_central_locking', 'is_power_steering',
       'is_driver_seat_height_adjustable', 'is_day_night_rear_view_mirror',
       'is_ecw', 'is_speed_alert', 'ncap_rating'],
      dtype='object')

In [36]:
Y

0        0
1        0
2        0
3        0
4        0
        ..
58587    0
58588    0
58589    0
58590    0
58591    0
Name: claim_status, Length: 58592, dtype: int64

In [37]:
X.dtypes

subscription_length                 int64
vehicle_age                         int64
customer_age                        int64
region_code                         int32
region_density                      int64
segment                             int32
model                               int32
fuel_type                           int32
engine_type                         int32
airbags                             int64
is_esc                              int64
is_adjustable_steering              int64
is_tpms                             int64
is_parking_sensors                  int64
is_parking_camera                   int64
rear_brakes_type                    int64
displacement                        int64
cylinder                            int64
transmission_type                   int64
steering_type                       int64
turning_radius                      int64
length                              int64
width                               int64
gross_weight                        int64
is_front_fog_lights                 int64
is_rear_window_wiper                int64
is_rear_window_washer               int64
is_rear_window_defogger             int64
is_brake_assist                     int64
is_power_door_locks                 int64
is_central_locking                  int64
is_power_steering                   int64
is_driver_seat_height_adjustable    int64
is_day_night_rear_view_mirror       int64
is_ecw                              int64
is_speed_alert                      int64
ncap_rating                         int64
dtype: object

In [38]:
Y.dtypes

dtype('int64')

In [39]:
df['rear_brakes_type'] = df['rear_brakes_type'].map({'drum': 1, 'disc': 0})

In [40]:
df['transimission_type'] = df['rear_brakes_type'].map({'automatic': 1, 'manual': 0})

In [41]:
df['steering_type'] = df['steering_type'].map({'power': 1, 'electric': 0})

In [42]:
df.head()

,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,engine_type,airbags,...,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status,transimission_type
0,3,6,41,20,8794,4,5,1,3,6,...,1,1,1,1,0,1,1,3,0,NaN
1,10,9,35,11,27003,3,10,1,10,2,...,1,1,1,1,1,1,1,4,0,NaN
2,3,1,44,20,8794,4,5,1,3,6,...,1,1,1,1,0,1,1,3,0,NaN
3,6,2,44,1,73430,0,0,0,6,2,...,0,0,1,0,0,0,1,0,0,NaN
4,4,5,56,4,5410,2,6,1,4,2,...,1,1,1,0,0,1,1,5,0,NaN

In [43]:
df

,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,engine_type,airbags,...,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status,transimission_type
0,3,6,41,20,8794,4,5,1,3,6,...,1,1,1,1,0,1,1,3,0,NaN
1,10,9,35,11,27003,3,10,1,10,2,...,1,1,1,1,1,1,1,4,0,NaN
2,3,1,44,20,8794,4,5,1,3,6,...,1,1,1,1,0,1,1,3,0,NaN
3,6,2,44,1,73430,0,0,0,6,2,...,0,0,1,0,0,0,1,0,0,NaN
4,4,5,56,4,5410,2,6,1,4,2,...,1,1,1,0,0,1,1,5,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58587,8,13,48,17,34738,2,7,2,8,2,...,1,1,1,1,1,1,1,2,0,NaN
58588,3,11,37,15,4076,4,5,1,3,6,...,1,1,1,1,0,1,1,3,0,NaN
58589,8,11,35,20,8794,2,7,2,8,2,...,1,1,1,1,1,1,1,2,0,NaN
58590,8,18,44,20,8794,2,7,2,8,2,...,1,1,1,1,1,1,1,2,0,NaN
58591,8,2,49,3,34791,2,7,2,8,2,...,1,1,1,1,1,1,1,2,0,NaN

In [44]:
X.dtypes

subscription_length                 int64
vehicle_age                         int64
customer_age                        int64
region_code                         int32
region_density                      int64
segment                             int32
model                               int32
fuel_type                           int32
engine_type                         int32
airbags                             int64
is_esc                              int64
is_adjustable_steering              int64
is_tpms                             int64
is_parking_sensors                  int64
is_parking_camera                   int64
rear_brakes_type                    int64
displacement                        int64
cylinder                            int64
transmission_type                   int64
steering_type                       int64
turning_radius                      int64
length                              int64
width                               int64
gross_weight                        int64
is_front_fog_lights                 int64
is_rear_window_wiper                int64
is_rear_window_washer               int64
is_rear_window_defogger             int64
is_brake_assist                     int64
is_power_door_locks                 int64
is_central_locking                  int64
is_power_steering                   int64
is_driver_seat_height_adjustable    int64
is_day_night_rear_view_mirror       int64
is_ecw                              int64
is_speed_alert                      int64
ncap_rating                         int64
dtype: object

In [45]:
df

,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,engine_type,airbags,...,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status,transimission_type
0,3,6,41,20,8794,4,5,1,3,6,...,1,1,1,1,0,1,1,3,0,NaN
1,10,9,35,11,27003,3,10,1,10,2,...,1,1,1,1,1,1,1,4,0,NaN
2,3,1,44,20,8794,4,5,1,3,6,...,1,1,1,1,0,1,1,3,0,NaN
3,6,2,44,1,73430,0,0,0,6,2,...,0,0,1,0,0,0,1,0,0,NaN
4,4,5,56,4,5410,2,6,1,4,2,...,1,1,1,0,0,1,1,5,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58587,8,13,48,17,34738,2,7,2,8,2,...,1,1,1,1,1,1,1,2,0,NaN
58588,3,11,37,15,4076,4,5,1,3,6,...,1,1,1,1,0,1,1,3,0,NaN
58589,8,11,35,20,8794,2,7,2,8,2,...,1,1,1,1,1,1,1,2,0,NaN
58590,8,18,44,20,8794,2,7,2,8,2,...,1,1,1,1,1,1,1,2,0,NaN
58591,8,2,49,3,34791,2,7,2,8,2,...,1,1,1,1,1,1,1,2,0,NaN

In [46]:
df.head()

,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,engine_type,airbags,...,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status,transimission_type
0,3,6,41,20,8794,4,5,1,3,6,...,1,1,1,1,0,1,1,3,0,NaN
1,10,9,35,11,27003,3,10,1,10,2,...,1,1,1,1,1,1,1,4,0,NaN
2,3,1,44,20,8794,4,5,1,3,6,...,1,1,1,1,0,1,1,3,0,NaN
3,6,2,44,1,73430,0,0,0,6,2,...,0,0,1,0,0,0,1,0,0,NaN
4,4,5,56,4,5410,2,6,1,4,2,...,1,1,1,0,0,1,1,5,0,NaN

In [47]:
df.fillna(0)

,subscription_length,vehicle_age,customer_age,region_code,region_density,segment,model,fuel_type,engine_type,airbags,...,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,claim_status,transimission_type
0,3,6,41,20,8794,4,5,1,3,6,...,1,1,1,1,0,1,1,3,0,0.0
1,10,9,35,11,27003,3,10,1,10,2,...,1,1,1,1,1,1,1,4,0,0.0
2,3,1,44,20,8794,4,5,1,3,6,...,1,1,1,1,0,1,1,3,0,0.0
3,6,2,44,1,73430,0,0,0,6,2,...,0,0,1,0,0,0,1,0,0,0.0
4,4,5,56,4,5410,2,6,1,4,2,...,1,1,1,0,0,1,1,5,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58587,8,13,48,17,34738,2,7,2,8,2,...,1,1,1,1,1,1,1,2,0,0.0
58588,3,11,37,15,4076,4,5,1,3,6,...,1,1,1,1,0,1,1,3,0,0.0
58589,8,11,35,20,8794,2,7,2,8,2,...,1,1,1,1,1,1,1,2,0,0.0
58590,8,18,44,20,8794,2,7,2,8,2,...,1,1,1,1,1,1,1,2,0,0.0
58591,8,2,49,3,34791,2,7,2,8,2,...,1,1,1,1,1,1,1,2,0,0.0

In [48]:
X.dtypes

subscription_length                 int64
vehicle_age                         int64
customer_age                        int64
region_code                         int32
region_density                      int64
segment                             int32
model                               int32
fuel_type                           int32
engine_type                         int32
airbags                             int64
is_esc                              int64
is_adjustable_steering              int64
is_tpms                             int64
is_parking_sensors                  int64
is_parking_camera                   int64
rear_brakes_type                    int64
displacement                        int64
cylinder                            int64
transmission_type                   int64
steering_type                       int64
turning_radius                      int64
length                              int64
width                               int64
gross_weight                        int64
is_front_fog_lights                 int64
is_rear_window_wiper                int64
is_rear_window_washer               int64
is_rear_window_defogger             int64
is_brake_assist                     int64
is_power_door_locks                 int64
is_central_locking                  int64
is_power_steering                   int64
is_driver_seat_height_adjustable    int64
is_day_night_rear_view_mirror       int64
is_ecw                              int64
is_speed_alert                      int64
ncap_rating                         int64
dtype: object

In [51]:

df.to_csv("claim_insurance",index=False)